### ISSUE TITLE
Error when running node setup.js

### ISSUE THREAD

**Issue by MrClayPole** [HorizenOfficial/nodetracker#102]
I'm running Ubuntu 20.04 in an LXD container. When following the install guide as below I get "Segmentation Fault (core dump) error on the last command below.

sudo apt-get install npm -y && sudo npm install -g n && sudo n 10.12.0
cd ~/ && git clone https://github.com/HorizenOfficial/nodetracker.git
cd nodetracker
npm install
node setup.js

If I instead use NVM to install 10.12.0 on a clean install of Ubuntu 20.01 I get the error below when running "node setup.js"

/home/zen/nodetracker/zencfg.js:32
  lines.pop();
        ^

TypeError: Cannot read property 'pop' of undefined
    at Object.exports.getZenConfig (/home/zen/nodetracker/zencfg.js:32:9)
    at Object.<anonymous> (/home/zen/nodetracker/setup.js:262:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by MrClayPole** [comment]
I have also tried this on a clean build of Ubuntu 18.04 and followed the build guide up to the "node setup.js" and got the following error

/home/zen/nodetracker/zencfg.js:32
  lines.pop();
        ^

TypeError: Cannot read property 'pop' of undefined
    at Object.exports.getZenConfig (/home/zen/nodetracker/zencfg.js:32:9)
    at Object.<anonymous> (/home/zen/nodetracker/setup.js:262:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by MrClayPole** [comment]
Found than my ansible-playbook is was removing the list permissions from the .zen folder. This then blocked the nodetracker from reading the zen.conf. I've now fixed the "TypeError: Cannot read property 'pop' of undefined" but not the segmentation fault (core dump) on ubuntu 20.04. Seems like there is a mismatch between nodejs 10.19.0 in 20.04 and the required version of 10.12.0

**Comment by MrClayPole** [comment]
I've managed to work around the segmentation fault now on Ubuntu 20.04 with the following commands.

sudo apt remove nodejs npm --purge
sudo apt autoremov/usr/local/n/versions/node/10.12.0e

It's bizarre that removing npm after it's been installed and then npm still runs but it does fix the issue but it did for me.

**Comment by ADumaine** [comment]
Nodetracker should work fine with newer versions of node.js.  Many are running 12.x and 14.x.

The documentation was written when 10.x was moving to LTS.  Code and documentation updates have been pushed back multiple times due to higher priority issues on the tracking servers.

**Comment by MrClayPole** [comment]
Ok thanks, I feel the Segmentation fault it more an Ubuntu issue as running "npm" with no options seg fault's after an "apt install npm"
